(()=>{
const S=document.querySelector('#events'),KEY='fm_events_v1',NS='http://www.w3.org/2000/svg';
const types=[['Runway',6,24,0],['Stage',12,8,0],['DJ booth',6,3,0],['Bar',8,3,0],['Seating row',12,3,6],['Chair',2,2,1],['Round table',6,6,8],['Cocktail table',3,3,0],['Photo wall',10,2,0],['Check-in',6,3,0],['Merch table',6,3,0],['Florals / art',3,3,0],['Backstage',12,10,0],['Speaker',2,2,0],['Light',2,2,0],['Exit',4,2,0],['Restrooms',6,6,0],['Clear aisle',4,16,0],['Traffic arrow',2,10,0]];
const id=()=>crypto.randomUUID(),fresh=()=>({id:id(),name:'Gallery runway',w:40,h:60,items:[]}),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db;try{db=JSON.parse(localStorage.getItem(KEY));if(!db.layouts.length)throw Error();db.layouts.forEach(l=>{if(!Number.isFinite(l.w)||!Number.isFinite(l.h)||!Array.isArray(l.items))throw Error();});}catch{const l=fresh();db={active:l.id,layouts:[l]};}let L=db.layouts.find(l=>l.id===db.active)||db.layouts[0],sel=null,svg;
S.innerHTML='<div class="e-bar"><label>Saved layout<select id="ev-layout"></select></label><button id="ev-new">New</button><button id="ev-copy">Duplicate</button><label>Venue<select id="ev-preset"><option value="">Custom</option><option value="40,60">Gallery</option><option value="80,100">Warehouse</option><option value="60,60">Courtyard</option></select></label><label>Width / ft<input id="ev-w" type="number" min="10" max="300" step="0.5"></label><label>Length / ft<input id="ev-h" type="number" min="10" max="300" step="0.5"></label><button id="ev-reset">Reset</button><button id="ev-png">PNG</button><button id="ev-print">Print</button></div><div class="e-work"><aside class="e-tools"><h3>Place an element</h3><div class="e-palette"></div><p class="e-status">Tap to add or drag onto the floor.</p></aside><figure class="e-board"><div class="p-head"><h3>Production plan</h3><small id="ev-dim"></small></div><div id="ev-svg"></div><figcaption>Drag to move · snaps to 6″ · select to resize or rotate · arrow keys to nudge.</figcaption><p id="ev-status" class="e-status" role="status"></p></figure><aside class="e-inspector"><h3>Layout notes</h3><div class="e-stats"><div><strong id="ev-seats"></strong><span>planned seats</span></div><div><strong id="ev-area"></strong><span>square feet</span></div></div><label>Layout name<input id="ev-name" maxlength="100"></label><div class="e-edit"></div><div class="e-warnings" aria-live="polite"></div><p class="e-status">Concept only, not legal occupancy or a fire-code check. Table seating assumes chairs around the footprint; allow extra pull-out space. Confirm exits, accessibility and circulation with your venue.</p></aside></div><div class="e-schedule"></div>';
const q=s=>S.querySelector(s),node=(tag,attrs,parent)=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));parent.append(e);return e;};
function save(){db.active=L.id;try{localStorage.setItem(KEY,JSON.stringify(db));q('#ev-status').textContent='Autosaved on this device.';}catch{q('#ev-status').textContent='Storage unavailable. Export before leaving.';}}
function list(){q('#ev-layout').innerHTML=db.layouts.map(l=>'<option value="'+escape(l.id)+'" '+(l===L?'selected':'')+'>'+escape(l.name)+'</option>').join('');q('#ev-name').value=L.name;q('#ev-w').value=L.w;q('#ev-h').value=L.h;}
const bounds=i=>i.r%180?{w:i.h,h:i.w}:{w:i.w,h:i.h};
function fit(i){const b=bounds(i);i.x=Math.max(b.w/2,Math.min(L.w-b.w/2,i.x));i.y=Math.max(b.h/2,Math.min(L.h-b.h/2,i.y));}
function add(n,x=L.w/2,y=L.h/2){const t=types[n],i={id:id(),type:n,label:t[0],w:Math.min(t[1],L.w),h:Math.min(t[2],L.h),seats:t[3],x,y,r:0,notes:''};fit(i);L.items.push(i);sel=i.id;save();draw();edit();}
types.forEach((t,n)=>{const b=document.createElement('button');b.textContent=t[0];b.draggable=true;b.onclick=()=>add(n);b.ondragstart=e=>e.dataTransfer.setData('text/plain',String(n));q('.e-palette').append(b);});
function point(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
function draw(){q('#ev-svg').innerHTML='';svg=node('svg',{xmlns:NS,viewBox:'-3 -4 '+(L.w+6)+' '+(L.h+9),role:'group','aria-label':L.name+' event plan','font-family':'monospace'},q('#ev-svg'));node('rect',{x:-3,y:-4,width:L.w+6,height:L.h+9,fill:'#f5f1ea'},svg);
for(let x=0;x<=L.w;x++)node('line',{x1:x,y1:0,x2:x,y2:L.h,stroke:x%5?'#e5ddd2':'#cfc6ba','stroke-width':.04},svg);for(let y=0;y<=L.h;y++)node('line',{x1:0,y1:y,x2:L.w,y2:y,stroke:y%5?'#e5ddd2':'#cfc6ba','stroke-width':.04},svg);node('rect',{width:L.w,height:L.h,fill:'none',stroke:'#1a1714','stroke-width':.18},svg);node('text',{x:0,y:-1.4,'font-size':1.1,fill:'#1a1714'},svg).textContent=L.name+' · '+L.w+'′ × '+L.h+'′';
L.items.forEach((i,n)=>{const g=node('g',{class:'e-item',transform:'translate('+i.x+' '+i.y+')',tabindex:0,role:'button','aria-label':i.label,'data-id':i.id},svg),r=node('g',{transform:'rotate('+i.r+')'},g),color=i.type>=17?'#2f6f8f':i.type===15?'#659788':i.type<3?'#b5482a':'#8a8178',a={fill:color,'fill-opacity':.2,stroke:sel===i.id?'#b5482a':color,'stroke-width':sel===i.id?.22:.1};
if([6,7,11].includes(i.type))node('ellipse',{...a,rx:i.w/2,ry:i.h/2},r);else node('rect',{...a,x:-i.w/2,y:-i.h/2,width:i.w,height:i.h,'stroke-dasharray':i.type===17?'.4 .3':'none'},r);
if(i.type===18)node('path',{d:'M0 '+i.h/2+'V'+(-i.h/2)+'m'+(-i.w/2)+' '+i.w+'L0 '+(-i.h/2)+'l'+i.w/2+' '+i.w,fill:'none',stroke:color,'stroke-width':.2},r);
node('text',{'text-anchor':'middle',y:.3,'font-size':Math.min(1,i.w/7),fill:'#1a1714','pointer-events':'none'},g).textContent=(n+1)+' '+(i.type===18?'':i.label);node('title',{},g).textContent=i.label+' · '+i.w+' × '+i.h+' ft';let d;
g.onpointerdown=e=>{e.preventDefault();const p=point(e);sel=i.id;d={x:p.x-i.x,y:p.y-i.y};g.setPointerCapture(e.pointerId);};g.onpointermove=e=>{if(!d)return;const p=point(e);i.x=Math.round((p.x-d.x)*2)/2;i.y=Math.round((p.y-d.y)*2)/2;fit(i);g.setAttribute('transform','translate('+i.x+' '+i.y+')');};const end=()=>{if(!d)return;d=null;save();draw();edit();};g.onpointerup=end;g.onpointercancel=end;g.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();sel=i.id;draw();edit();}const v={ArrowLeft:[-.5,0],ArrowRight:[.5,0],ArrowUp:[0,-.5],ArrowDown:[0,.5]}[e.key];if(v){e.preventDefault();sel=i.id;i.x+=v[0];i.y+=v[1];fit(i);g.setAttribute('transform','translate('+i.x+' '+i.y+')');save();summary();edit();}};});
svg.ondragover=e=>e.preventDefault();svg.ondrop=e=>{e.preventDefault();const data=e.dataTransfer.getData('text/plain'),n=Number(data);if(data!==''&&types[n]){const p=point(e);add(n,Math.round(p.x*2)/2,Math.round(p.y*2)/2);}};q('#ev-dim').textContent=L.w+'′ × '+L.h+'′';summary();}
function summary(){q('#ev-seats').textContent=L.items.reduce((s,i)=>s+i.seats,0);q('#ev-area').textContent=L.w*L.h;const warn=[];L.items.forEach((a,n)=>{const A=bounds(a);if(A.w>L.w||A.h>L.h||a.x-A.w/2<0||a.y-A.h/2<0)warn.push(a.label+' outside venue.');if(a.type===18)return;L.items.slice(n+1).forEach(b=>{if(b.type===18)return;const B=bounds(b),x=Math.abs(a.x-b.x)-(A.w+B.w)/2,y=Math.abs(a.y-b.y)-(A.h+B.h)/2;if(x<0&&y<0)warn.push(a.label+' / '+b.label+' overlap'+([a.type,b.type].includes(17)?' in reserved aisle.':'.'));else if(x<3&&y<3&&a.type!==17&&b.type!==17)warn.push(a.label+' / '+b.label+' less than 3′ apart.');});});if(!L.items.some(i=>i.type===15))warn.push('Mark exits and keep their access clear.');q('.e-warnings').textContent=warn.join(' ')||'No footprint conflicts flagged. Confirm circulation with venue.';q('.e-schedule').innerHTML='<table><thead><tr><th>ID</th><th>Element</th><th>Footprint / ft</th><th>Rotation</th><th>Seats</th><th>Notes</th></tr></thead><tbody>'+L.items.map((i,n)=>'<tr><td>'+(n+1)+'</td><td>'+escape(i.label)+'</td><td>'+i.w+' × '+i.h+'</td><td>'+i.r+'°</td><td>'+i.seats+'</td><td>'+escape(i.notes)+'</td></tr>').join('')+'</tbody></table>';}
function edit(){const i=L.items.find(i=>i.id===sel),box=q('.e-edit');if(!i){box.innerHTML='<p class="e-status">Select an element to resize, rotate or add notes.</p>';return;}box.innerHTML='<label>Element<input data-k="label" maxlength="80" value="'+escape(i.label)+'"></label>'+['w','h','seats'].map(k=>'<label>'+({w:'Width / ft',h:'Depth / ft',seats:'Planned seats'}[k])+'<input data-k="'+k+'" type="number" min="'+(k==='seats'?0:.5)+'" max="'+(k==='seats'?1000:300)+'" step="'+(k==='seats'?1:.5)+'" value="'+i[k]+'"></label>').join('')+'<label>Notes<textarea data-k="notes" maxlength="1000">'+escape(i.notes)+'</textarea></label><button id="ev-rotate">Rotate 90° · '+i.r+'°</button><button id="ev-itemcopy">Duplicate item</button><button id="ev-remove">Remove item</button>';box.querySelectorAll('[data-k]').forEach(f=>f.onchange=()=>{if(!f.checkValidity())return;const k=f.dataset.k;i[k]=['w','h','seats'].includes(k)?Number(f.value):f.value;fit(i);save();draw();});q('#ev-rotate').onclick=()=>{i.r=(i.r+90)%360;fit(i);save();draw();edit();};q('#ev-itemcopy').onclick=()=>{const c={...i,id:id(),x:i.x+3,y:i.y+3};fit(c);L.items.push(c);sel=c.id;save();draw();edit();};q('#ev-remove').onclick=()=>{L.items=L.items.filter(a=>a.id!==sel);sel=null;save();draw();edit();};}
q('#ev-layout').onchange=e=>{L=db.layouts.find(l=>l.id===e.target.value);sel=null;list();save();draw();edit();};q('#ev-name').onchange=e=>{L.name=e.target.value.trim()||'Untitled layout';list();save();draw();};function resize(w,h){L.w=w;L.h=h;L.items.forEach(fit);list();save();draw();edit();}['#ev-w','#ev-h'].forEach(k=>q(k).onchange=()=>{if(q('#ev-w').checkValidity()&&q('#ev-h').checkValidity())resize(Number(q('#ev-w').value),Number(q('#ev-h').value));});q('#ev-preset').onchange=e=>{if(e.target.value)resize(...e.target.value.split(',').map(Number));};
q('#ev-new').onclick=()=>{L=fresh();L.name='Untitled layout';db.layouts.push(L);sel=null;list();save();draw();edit();};q('#ev-copy').onclick=()=>{L={...L,id:id(),name:L.name+' / copy',items:L.items.map(i=>({...i,id:id()}))};db.layouts.push(L);sel=null;list();save();draw();edit();};q('#ev-reset').onclick=()=>{if(!confirm('Clear this layout? Other saved layouts stay unchanged.'))return;L.items=[];sel=null;save();draw();edit();};q('#ev-print').onclick=()=>print();q('#ev-png').onclick=()=>{const clone=svg.cloneNode(true),v=svg.viewBox.baseVal,scale=Math.min(24,2400/Math.max(v.width,v.height));clone.setAttribute('width',Math.ceil(v.width*scale));clone.setAttribute('height',Math.ceil(v.height*scale));const u=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'})),im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=Math.ceil(v.width*scale);c.height=Math.ceil(v.height*scale);c.getContext('2d').drawImage(im,0,0);URL.revokeObjectURL(u);c.toBlob(b=>{if(!b)return;const a=document.createElement('a'),url=URL.createObjectURL(b);a.href=url;a.download='event-layout.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});};im.onerror=()=>{URL.revokeObjectURL(u);q('#ev-status').textContent='Export failed. Try Print.';};im.src=u;};
document.querySelectorAll('.views button').forEach(b=>b.addEventListener('click',()=>{S.hidden=b.dataset.view!=='events';}));list();draw();edit();save();if(location.hash==='#events')document.querySelector('[data-view=events]').click();
})();